-- AlterTable
ALTER TABLE "Economy" ALTER COLUMN "holding" SET DEFAULT 10000.00,
ALTER COLUMN "holding" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bank" SET DEFAULT 0.00,
ALTER COLUMN "bank" SET DATA TYPE DOUBLE PRECISION;
